# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.column_statistics_request_from import ColumnStatisticsRequestFrom
from gooddata_api_client.models.frequency_properties import FrequencyProperties
from gooddata_api_client.models.histogram_properties import HistogramProperties
from typing import Optional, Set
from typing_extensions import Self

class ColumnStatisticsRequest(BaseModel):
    """
    A request to retrieve statistics for a column.
    """ # noqa: E501
    column_name: StrictStr = Field(alias="columnName")
    frequency: Optional[FrequencyProperties] = None
    var_from: ColumnStatisticsRequestFrom = Field(alias="from")
    histogram: Optional[HistogramProperties] = None
    statistics: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["columnName", "frequency", "from", "histogram", "statistics"]

    @field_validator('statistics')
    def statistics_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['COUNT', 'COUNT_NULL', 'COUNT_UNIQUE', 'AVG', 'STDDEV', 'MIN', 'MAX', 'PERCENTILE_25', 'PERCENTILE_50', 'PERCENTILE_75']):
                raise ValueError("each list item must be one of ('COUNT', 'COUNT_NULL', 'COUNT_UNIQUE', 'AVG', 'STDDEV', 'MIN', 'MAX', 'PERCENTILE_25', 'PERCENTILE_50', 'PERCENTILE_75')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ColumnStatisticsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of frequency
        if self.frequency:
            _dict['frequency'] = self.frequency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of histogram
        if self.histogram:
            _dict['histogram'] = self.histogram.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ColumnStatisticsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "columnName": obj.get("columnName"),
            "frequency": FrequencyProperties.from_dict(obj["frequency"]) if obj.get("frequency") is not None else None,
            "from": ColumnStatisticsRequestFrom.from_dict(obj["from"]) if obj.get("from") is not None else None,
            "histogram": HistogramProperties.from_dict(obj["histogram"]) if obj.get("histogram") is not None else None,
            "statistics": obj.get("statistics")
        })
        return _obj


