# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gooddata_api_client.models.declarative_notification_channel_destination import DeclarativeNotificationChannelDestination
from typing import Optional, Set
from typing_extensions import Self

class DeclarativeNotificationChannel(BaseModel):
    """
    A declarative form of a particular notification channel.
    """ # noqa: E501
    allowed_recipients: Optional[StrictStr] = Field(default='INTERNAL', description="Allowed recipients of notifications from this channel. CREATOR - only the creator INTERNAL - all users within the organization EXTERNAL - all recipients including those outside the organization ", alias="allowedRecipients")
    custom_dashboard_url: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Custom dashboard url that is going to be used in the notification. If not specified it is going to be deduced based on the context. Allowed placeholders are: {workspaceId} {dashboardId} {automationId} {asOfDate} ", alias="customDashboardUrl")
    dashboard_link_visibility: Optional[StrictStr] = Field(default='INTERNAL_ONLY', description="Dashboard link visibility in notifications. HIDDEN - the link will not be included INTERNAL_ONLY - only internal users will see the link ALL - all users will see the link ", alias="dashboardLinkVisibility")
    description: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Description of a notification channel.")
    destination: Optional[DeclarativeNotificationChannelDestination] = None
    destination_type: Optional[StrictStr] = Field(default=None, alias="destinationType")
    id: Annotated[str, Field(strict=True)] = Field(description="Identifier of a notification channel")
    in_platform_notification: Optional[StrictStr] = Field(default='DISABLED', description="In-platform notifications configuration. No effect if the destination type is IN_PLATFORM. DISABLED - in-platform notifications are not sent ENABLED - in-platform notifications are sent in addition to the regular notifications ", alias="inPlatformNotification")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Name of a notification channel.")
    notification_source: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Human-readable description of the source of the notification. If specified, this propertywill be included in the notifications to this channel.Allowed placeholders are: {{workspaceId}} {{workspaceName}} {{workspaceDescription}} {{dashboardId}} {{dashboardName}} {{dashboardDescription}} ", alias="notificationSource")
    __properties: ClassVar[List[str]] = ["allowedRecipients", "customDashboardUrl", "dashboardLinkVisibility", "description", "destination", "destinationType", "id", "inPlatformNotification", "name", "notificationSource"]

    @field_validator('allowed_recipients')
    def allowed_recipients_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREATOR', 'INTERNAL', 'EXTERNAL']):
            raise ValueError("must be one of enum values ('CREATOR', 'INTERNAL', 'EXTERNAL')")
        return value

    @field_validator('dashboard_link_visibility')
    def dashboard_link_visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['HIDDEN', 'INTERNAL_ONLY', 'ALL']):
            raise ValueError("must be one of enum values ('HIDDEN', 'INTERNAL_ONLY', 'ALL')")
        return value

    @field_validator('destination_type')
    def destination_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['WEBHOOK', 'SMTP', 'DEFAULT_SMTP', 'IN_PLATFORM']):
            raise ValueError("must be one of enum values ('WEBHOOK', 'SMTP', 'DEFAULT_SMTP', 'IN_PLATFORM')")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!\.)[.A-Za-z0-9_-]{1,255}$", value):
            raise ValueError(r"must validate the regular expression /^(?!\.)[.A-Za-z0-9_-]{1,255}$/")
        return value

    @field_validator('in_platform_notification')
    def in_platform_notification_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DISABLED', 'ENABLED']):
            raise ValueError("must be one of enum values ('DISABLED', 'ENABLED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeclarativeNotificationChannel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "destination_type",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # set to None if destination_type (nullable) is None
        # and model_fields_set contains the field
        if self.destination_type is None and "destination_type" in self.model_fields_set:
            _dict['destinationType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeclarativeNotificationChannel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowedRecipients": obj.get("allowedRecipients") if obj.get("allowedRecipients") is not None else 'INTERNAL',
            "customDashboardUrl": obj.get("customDashboardUrl"),
            "dashboardLinkVisibility": obj.get("dashboardLinkVisibility") if obj.get("dashboardLinkVisibility") is not None else 'INTERNAL_ONLY',
            "description": obj.get("description"),
            "destination": DeclarativeNotificationChannelDestination.from_dict(obj["destination"]) if obj.get("destination") is not None else None,
            "destinationType": obj.get("destinationType"),
            "id": obj.get("id"),
            "inPlatformNotification": obj.get("inPlatformNotification") if obj.get("inPlatformNotification") is not None else 'DISABLED',
            "name": obj.get("name"),
            "notificationSource": obj.get("notificationSource")
        })
        return _obj


