# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gooddata_api_client.models.content_slide_template import ContentSlideTemplate
from typing import Optional, Set
from typing_extensions import Self

class JsonApiExportTemplateInAttributesWidgetSlidesTemplate(BaseModel):
    """
    Template for widget slides export. Available variables: {{currentPageNumber}}, {{dashboardDateFilters}}, {{dashboardDescription}}, {{dashboardFilters}}, {{dashboardId}}, {{dashboardName}}, {{dashboardTags}}, {{dashboardUrl}}, {{exportedAt}}, {{exportedBy}}, {{logo}}, {{totalPages}}, {{workspaceId}}, {{workspaceName}}
    """ # noqa: E501
    applied_on: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="Export types this template applies to.", alias="appliedOn")
    content_slide: Optional[ContentSlideTemplate] = Field(default=None, alias="contentSlide")
    __properties: ClassVar[List[str]] = ["appliedOn", "contentSlide"]

    @field_validator('applied_on')
    def applied_on_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['PDF', 'PPTX']):
                raise ValueError("each list item must be one of ('PDF', 'PPTX')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiExportTemplateInAttributesWidgetSlidesTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content_slide
        if self.content_slide:
            _dict['contentSlide'] = self.content_slide.to_dict()
        # set to None if content_slide (nullable) is None
        # and model_fields_set contains the field
        if self.content_slide is None and "content_slide" in self.model_fields_set:
            _dict['contentSlide'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiExportTemplateInAttributesWidgetSlidesTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appliedOn": obj.get("appliedOn"),
            "contentSlide": ContentSlideTemplate.from_dict(obj["contentSlide"]) if obj.get("contentSlide") is not None else None
        })
        return _obj


