# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from gooddata_api_client.models.json_api_identity_provider_out_with_links import JsonApiIdentityProviderOutWithLinks
from gooddata_api_client.models.json_api_user_group_out_with_links import JsonApiUserGroupOutWithLinks
from gooddata_api_client.models.json_api_user_out_with_links import JsonApiUserOutWithLinks
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

JSONAPIORGANIZATIONOUTINCLUDES_ONE_OF_SCHEMAS = ["JsonApiIdentityProviderOutWithLinks", "JsonApiUserGroupOutWithLinks", "JsonApiUserOutWithLinks"]

class JsonApiOrganizationOutIncludes(BaseModel):
    """
    JsonApiOrganizationOutIncludes
    """
    # data type: JsonApiUserOutWithLinks
    oneof_schema_1_validator: Optional[JsonApiUserOutWithLinks] = None
    # data type: JsonApiUserGroupOutWithLinks
    oneof_schema_2_validator: Optional[JsonApiUserGroupOutWithLinks] = None
    # data type: JsonApiIdentityProviderOutWithLinks
    oneof_schema_3_validator: Optional[JsonApiIdentityProviderOutWithLinks] = None
    actual_instance: Optional[Union[JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks]] = None
    one_of_schemas: Set[str] = { "JsonApiIdentityProviderOutWithLinks", "JsonApiUserGroupOutWithLinks", "JsonApiUserOutWithLinks" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = JsonApiOrganizationOutIncludes.model_construct()
        error_messages = []
        match = 0
        # validate data type: JsonApiUserOutWithLinks
        if not isinstance(v, JsonApiUserOutWithLinks):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JsonApiUserOutWithLinks`")
        else:
            match += 1
        # validate data type: JsonApiUserGroupOutWithLinks
        if not isinstance(v, JsonApiUserGroupOutWithLinks):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JsonApiUserGroupOutWithLinks`")
        else:
            match += 1
        # validate data type: JsonApiIdentityProviderOutWithLinks
        if not isinstance(v, JsonApiIdentityProviderOutWithLinks):
            error_messages.append(f"Error! Input type `{type(v)}` is not `JsonApiIdentityProviderOutWithLinks`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in JsonApiOrganizationOutIncludes with oneOf schemas: JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in JsonApiOrganizationOutIncludes with oneOf schemas: JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into JsonApiUserOutWithLinks
        try:
            instance.actual_instance = JsonApiUserOutWithLinks.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JsonApiUserGroupOutWithLinks
        try:
            instance.actual_instance = JsonApiUserGroupOutWithLinks.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into JsonApiIdentityProviderOutWithLinks
        try:
            instance.actual_instance = JsonApiIdentityProviderOutWithLinks.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into JsonApiOrganizationOutIncludes with oneOf schemas: JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into JsonApiOrganizationOutIncludes with oneOf schemas: JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], JsonApiIdentityProviderOutWithLinks, JsonApiUserGroupOutWithLinks, JsonApiUserOutWithLinks]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


