# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.declarative_table import DeclarativeTable
from gooddata_api_client.models.pdm_sql import PdmSql
from gooddata_api_client.models.table_override import TableOverride
from typing import Optional, Set
from typing_extensions import Self

class PdmLdmRequest(BaseModel):
    """
    PDM additions wrapper.
    """ # noqa: E501
    sqls: Optional[List[PdmSql]] = Field(default=None, description="List of SQL datasets.")
    table_overrides: Optional[List[TableOverride]] = Field(default=None, description="(BETA) List of table overrides.", alias="tableOverrides")
    tables: Optional[List[DeclarativeTable]] = Field(default=None, description="List of physical database tables.")
    __properties: ClassVar[List[str]] = ["sqls", "tableOverrides", "tables"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PdmLdmRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sqls (list)
        _items = []
        if self.sqls:
            for _item_sqls in self.sqls:
                if _item_sqls:
                    _items.append(_item_sqls.to_dict())
            _dict['sqls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in table_overrides (list)
        _items = []
        if self.table_overrides:
            for _item_table_overrides in self.table_overrides:
                if _item_table_overrides:
                    _items.append(_item_table_overrides.to_dict())
            _dict['tableOverrides'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tables (list)
        _items = []
        if self.tables:
            for _item_tables in self.tables:
                if _item_tables:
                    _items.append(_item_tables.to_dict())
            _dict['tables'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PdmLdmRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sqls": [PdmSql.from_dict(_item) for _item in obj["sqls"]] if obj.get("sqls") is not None else None,
            "tableOverrides": [TableOverride.from_dict(_item) for _item in obj["tableOverrides"]] if obj.get("tableOverrides") is not None else None,
            "tables": [DeclarativeTable.from_dict(_item) for _item in obj["tables"]] if obj.get("tables") is not None else None
        })
        return _obj


