# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gooddata_api_client import schemas  # noqa: F401


class AacAnalyticsModel(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    AAC analytics model representation compatible with Analytics-as-Code YAML format.
    """


    class MetaOapg:
        
        class properties:
            
            
            class attribute_hierarchies(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AacAttributeHierarchy']:
                        return AacAttributeHierarchy
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AacAttributeHierarchy'], typing.List['AacAttributeHierarchy']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attribute_hierarchies':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AacAttributeHierarchy':
                    return super().__getitem__(i)
            
            
            class dashboards(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AacDashboard']:
                        return AacDashboard
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AacDashboard'], typing.List['AacDashboard']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dashboards':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AacDashboard':
                    return super().__getitem__(i)
            
            
            class metrics(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AacMetric']:
                        return AacMetric
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AacMetric'], typing.List['AacMetric']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'metrics':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AacMetric':
                    return super().__getitem__(i)
            
            
            class plugins(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AacPlugin']:
                        return AacPlugin
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AacPlugin'], typing.List['AacPlugin']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'plugins':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AacPlugin':
                    return super().__getitem__(i)
            
            
            class visualizations(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AacVisualization']:
                        return AacVisualization
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AacVisualization'], typing.List['AacVisualization']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'visualizations':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AacVisualization':
                    return super().__getitem__(i)
            __annotations__ = {
                "attribute_hierarchies": attribute_hierarchies,
                "dashboards": dashboards,
                "metrics": metrics,
                "plugins": plugins,
                "visualizations": visualizations,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attribute_hierarchies"]) -> MetaOapg.properties.attribute_hierarchies: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dashboards"]) -> MetaOapg.properties.dashboards: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metrics"]) -> MetaOapg.properties.metrics: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["plugins"]) -> MetaOapg.properties.plugins: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["visualizations"]) -> MetaOapg.properties.visualizations: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["attribute_hierarchies", "dashboards", "metrics", "plugins", "visualizations", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attribute_hierarchies"]) -> typing.Union[MetaOapg.properties.attribute_hierarchies, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dashboards"]) -> typing.Union[MetaOapg.properties.dashboards, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metrics"]) -> typing.Union[MetaOapg.properties.metrics, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["plugins"]) -> typing.Union[MetaOapg.properties.plugins, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["visualizations"]) -> typing.Union[MetaOapg.properties.visualizations, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attribute_hierarchies", "dashboards", "metrics", "plugins", "visualizations", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        attribute_hierarchies: typing.Union[MetaOapg.properties.attribute_hierarchies, list, tuple, schemas.Unset] = schemas.unset,
        dashboards: typing.Union[MetaOapg.properties.dashboards, list, tuple, schemas.Unset] = schemas.unset,
        metrics: typing.Union[MetaOapg.properties.metrics, list, tuple, schemas.Unset] = schemas.unset,
        plugins: typing.Union[MetaOapg.properties.plugins, list, tuple, schemas.Unset] = schemas.unset,
        visualizations: typing.Union[MetaOapg.properties.visualizations, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AacAnalyticsModel':
        return super().__new__(
            cls,
            *_args,
            attribute_hierarchies=attribute_hierarchies,
            dashboards=dashboards,
            metrics=metrics,
            plugins=plugins,
            visualizations=visualizations,
            _configuration=_configuration,
            **kwargs,
        )

from gooddata_api_client.model.aac_attribute_hierarchy import AacAttributeHierarchy
from gooddata_api_client.model.aac_dashboard import AacDashboard
from gooddata_api_client.model.aac_metric import AacMetric
from gooddata_api_client.model.aac_plugin import AacPlugin
from gooddata_api_client.model.aac_visualization import AacVisualization
