# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gooddata_api_client import schemas  # noqa: F401


class ChatHistoryRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            chatHistoryInteractionId = schemas.StrSchema
            reset = schemas.BoolSchema
            
            
            class responseState(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def SUCCESSFUL(cls):
                    return cls("SUCCESSFUL")
                
                @schemas.classproperty
                def UNEXPECTED_ERROR(cls):
                    return cls("UNEXPECTED_ERROR")
                
                @schemas.classproperty
                def NOT_FOUND_ATTRIBUTES(cls):
                    return cls("NOT_FOUND_ATTRIBUTES")
                
                @schemas.classproperty
                def TOO_MANY_DATA_POINTS(cls):
                    return cls("TOO_MANY_DATA_POINTS")
                
                @schemas.classproperty
                def NO_DATA(cls):
                    return cls("NO_DATA")
                
                @schemas.classproperty
                def NO_RESULTS(cls):
                    return cls("NO_RESULTS")
                
                @schemas.classproperty
                def OUT_OF_TOPIC(cls):
                    return cls("OUT_OF_TOPIC")
        
            @staticmethod
            def savedVisualization() -> typing.Type['SavedVisualization']:
                return SavedVisualization
            threadIdSuffix = schemas.StrSchema
            
            
            class userFeedback(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def POSITIVE(cls):
                    return cls("POSITIVE")
                
                @schemas.classproperty
                def NEGATIVE(cls):
                    return cls("NEGATIVE")
                
                @schemas.classproperty
                def NONE(cls):
                    return cls("NONE")
            userTextFeedback = schemas.StrSchema
            __annotations__ = {
                "chatHistoryInteractionId": chatHistoryInteractionId,
                "reset": reset,
                "responseState": responseState,
                "savedVisualization": savedVisualization,
                "threadIdSuffix": threadIdSuffix,
                "userFeedback": userFeedback,
                "userTextFeedback": userTextFeedback,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chatHistoryInteractionId"]) -> MetaOapg.properties.chatHistoryInteractionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reset"]) -> MetaOapg.properties.reset: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["responseState"]) -> MetaOapg.properties.responseState: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["savedVisualization"]) -> 'SavedVisualization': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threadIdSuffix"]) -> MetaOapg.properties.threadIdSuffix: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userFeedback"]) -> MetaOapg.properties.userFeedback: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userTextFeedback"]) -> MetaOapg.properties.userTextFeedback: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["chatHistoryInteractionId", "reset", "responseState", "savedVisualization", "threadIdSuffix", "userFeedback", "userTextFeedback", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chatHistoryInteractionId"]) -> typing.Union[MetaOapg.properties.chatHistoryInteractionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reset"]) -> typing.Union[MetaOapg.properties.reset, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["responseState"]) -> typing.Union[MetaOapg.properties.responseState, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["savedVisualization"]) -> typing.Union['SavedVisualization', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threadIdSuffix"]) -> typing.Union[MetaOapg.properties.threadIdSuffix, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userFeedback"]) -> typing.Union[MetaOapg.properties.userFeedback, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userTextFeedback"]) -> typing.Union[MetaOapg.properties.userTextFeedback, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["chatHistoryInteractionId", "reset", "responseState", "savedVisualization", "threadIdSuffix", "userFeedback", "userTextFeedback", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        chatHistoryInteractionId: typing.Union[MetaOapg.properties.chatHistoryInteractionId, str, schemas.Unset] = schemas.unset,
        reset: typing.Union[MetaOapg.properties.reset, bool, schemas.Unset] = schemas.unset,
        responseState: typing.Union[MetaOapg.properties.responseState, str, schemas.Unset] = schemas.unset,
        savedVisualization: typing.Union['SavedVisualization', schemas.Unset] = schemas.unset,
        threadIdSuffix: typing.Union[MetaOapg.properties.threadIdSuffix, str, schemas.Unset] = schemas.unset,
        userFeedback: typing.Union[MetaOapg.properties.userFeedback, str, schemas.Unset] = schemas.unset,
        userTextFeedback: typing.Union[MetaOapg.properties.userTextFeedback, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ChatHistoryRequest':
        return super().__new__(
            cls,
            *_args,
            chatHistoryInteractionId=chatHistoryInteractionId,
            reset=reset,
            responseState=responseState,
            savedVisualization=savedVisualization,
            threadIdSuffix=threadIdSuffix,
            userFeedback=userFeedback,
            userTextFeedback=userTextFeedback,
            _configuration=_configuration,
            **kwargs,
        )

from gooddata_api_client.model.saved_visualization import SavedVisualization
