# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gooddata_api_client import schemas  # noqa: F401


class ChatRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "question",
        }
        
        class properties:
            
            
            class question(
                schemas.StrSchema
            ):
                pass
            
            
            class allowedRelationshipTypes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['AllowedRelationshipType']:
                        return AllowedRelationshipType
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['AllowedRelationshipType'], typing.List['AllowedRelationshipType']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'allowedRelationshipTypes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AllowedRelationshipType':
                    return super().__getitem__(i)
            includeHidden = schemas.BoolSchema
            limitCreate = schemas.Int32Schema
            limitCreateContext = schemas.Int32Schema
            limitSearch = schemas.Int32Schema
            
            
            class objectTypes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.EnumBase,
                        schemas.StrSchema
                    ):
                        
                        @schemas.classproperty
                        def ATTRIBUTE(cls):
                            return cls("attribute")
                        
                        @schemas.classproperty
                        def METRIC(cls):
                            return cls("metric")
                        
                        @schemas.classproperty
                        def FACT(cls):
                            return cls("fact")
                        
                        @schemas.classproperty
                        def LABEL(cls):
                            return cls("label")
                        
                        @schemas.classproperty
                        def DATE(cls):
                            return cls("date")
                        
                        @schemas.classproperty
                        def DATASET(cls):
                            return cls("dataset")
                        
                        @schemas.classproperty
                        def VISUALIZATION(cls):
                            return cls("visualization")
                        
                        @schemas.classproperty
                        def DASHBOARD(cls):
                            return cls("dashboard")
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'objectTypes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            relevantScoreThreshold = schemas.Float64Schema
            searchScoreThreshold = schemas.Float64Schema
            threadIdSuffix = schemas.StrSchema
            titleToDescriptorRatio = schemas.Float64Schema
        
            @staticmethod
            def userContext() -> typing.Type['UserContext']:
                return UserContext
            __annotations__ = {
                "question": question,
                "allowedRelationshipTypes": allowedRelationshipTypes,
                "includeHidden": includeHidden,
                "limitCreate": limitCreate,
                "limitCreateContext": limitCreateContext,
                "limitSearch": limitSearch,
                "objectTypes": objectTypes,
                "relevantScoreThreshold": relevantScoreThreshold,
                "searchScoreThreshold": searchScoreThreshold,
                "threadIdSuffix": threadIdSuffix,
                "titleToDescriptorRatio": titleToDescriptorRatio,
                "userContext": userContext,
            }
    
    question: MetaOapg.properties.question
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["question"]) -> MetaOapg.properties.question: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowedRelationshipTypes"]) -> MetaOapg.properties.allowedRelationshipTypes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeHidden"]) -> MetaOapg.properties.includeHidden: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limitCreate"]) -> MetaOapg.properties.limitCreate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limitCreateContext"]) -> MetaOapg.properties.limitCreateContext: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limitSearch"]) -> MetaOapg.properties.limitSearch: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["objectTypes"]) -> MetaOapg.properties.objectTypes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["relevantScoreThreshold"]) -> MetaOapg.properties.relevantScoreThreshold: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["searchScoreThreshold"]) -> MetaOapg.properties.searchScoreThreshold: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threadIdSuffix"]) -> MetaOapg.properties.threadIdSuffix: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["titleToDescriptorRatio"]) -> MetaOapg.properties.titleToDescriptorRatio: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userContext"]) -> 'UserContext': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["question", "allowedRelationshipTypes", "includeHidden", "limitCreate", "limitCreateContext", "limitSearch", "objectTypes", "relevantScoreThreshold", "searchScoreThreshold", "threadIdSuffix", "titleToDescriptorRatio", "userContext", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["question"]) -> MetaOapg.properties.question: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowedRelationshipTypes"]) -> typing.Union[MetaOapg.properties.allowedRelationshipTypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeHidden"]) -> typing.Union[MetaOapg.properties.includeHidden, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limitCreate"]) -> typing.Union[MetaOapg.properties.limitCreate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limitCreateContext"]) -> typing.Union[MetaOapg.properties.limitCreateContext, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limitSearch"]) -> typing.Union[MetaOapg.properties.limitSearch, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["objectTypes"]) -> typing.Union[MetaOapg.properties.objectTypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["relevantScoreThreshold"]) -> typing.Union[MetaOapg.properties.relevantScoreThreshold, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["searchScoreThreshold"]) -> typing.Union[MetaOapg.properties.searchScoreThreshold, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threadIdSuffix"]) -> typing.Union[MetaOapg.properties.threadIdSuffix, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["titleToDescriptorRatio"]) -> typing.Union[MetaOapg.properties.titleToDescriptorRatio, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userContext"]) -> typing.Union['UserContext', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["question", "allowedRelationshipTypes", "includeHidden", "limitCreate", "limitCreateContext", "limitSearch", "objectTypes", "relevantScoreThreshold", "searchScoreThreshold", "threadIdSuffix", "titleToDescriptorRatio", "userContext", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        question: typing.Union[MetaOapg.properties.question, str, ],
        allowedRelationshipTypes: typing.Union[MetaOapg.properties.allowedRelationshipTypes, list, tuple, schemas.Unset] = schemas.unset,
        includeHidden: typing.Union[MetaOapg.properties.includeHidden, bool, schemas.Unset] = schemas.unset,
        limitCreate: typing.Union[MetaOapg.properties.limitCreate, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        limitCreateContext: typing.Union[MetaOapg.properties.limitCreateContext, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        limitSearch: typing.Union[MetaOapg.properties.limitSearch, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        objectTypes: typing.Union[MetaOapg.properties.objectTypes, list, tuple, schemas.Unset] = schemas.unset,
        relevantScoreThreshold: typing.Union[MetaOapg.properties.relevantScoreThreshold, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        searchScoreThreshold: typing.Union[MetaOapg.properties.searchScoreThreshold, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        threadIdSuffix: typing.Union[MetaOapg.properties.threadIdSuffix, str, schemas.Unset] = schemas.unset,
        titleToDescriptorRatio: typing.Union[MetaOapg.properties.titleToDescriptorRatio, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        userContext: typing.Union['UserContext', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ChatRequest':
        return super().__new__(
            cls,
            *_args,
            question=question,
            allowedRelationshipTypes=allowedRelationshipTypes,
            includeHidden=includeHidden,
            limitCreate=limitCreate,
            limitCreateContext=limitCreateContext,
            limitSearch=limitSearch,
            objectTypes=objectTypes,
            relevantScoreThreshold=relevantScoreThreshold,
            searchScoreThreshold=searchScoreThreshold,
            threadIdSuffix=threadIdSuffix,
            titleToDescriptorRatio=titleToDescriptorRatio,
            userContext=userContext,
            _configuration=_configuration,
            **kwargs,
        )

from gooddata_api_client.model.allowed_relationship_type import AllowedRelationshipType
from gooddata_api_client.model.user_context import UserContext
