# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gooddata_api_client import schemas  # noqa: F401


class ValidateLLMEndpointByIdRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            baseUrl = schemas.StrSchema
            llmModel = schemas.StrSchema
            llmOrganization = schemas.StrSchema
            provider = schemas.StrSchema
            token = schemas.StrSchema
            __annotations__ = {
                "baseUrl": baseUrl,
                "llmModel": llmModel,
                "llmOrganization": llmOrganization,
                "provider": provider,
                "token": token,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["baseUrl"]) -> MetaOapg.properties.baseUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["llmModel"]) -> MetaOapg.properties.llmModel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["llmOrganization"]) -> MetaOapg.properties.llmOrganization: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider"]) -> MetaOapg.properties.provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["baseUrl", "llmModel", "llmOrganization", "provider", "token", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["baseUrl"]) -> typing.Union[MetaOapg.properties.baseUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["llmModel"]) -> typing.Union[MetaOapg.properties.llmModel, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["llmOrganization"]) -> typing.Union[MetaOapg.properties.llmOrganization, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider"]) -> typing.Union[MetaOapg.properties.provider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["token"]) -> typing.Union[MetaOapg.properties.token, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["baseUrl", "llmModel", "llmOrganization", "provider", "token", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        baseUrl: typing.Union[MetaOapg.properties.baseUrl, str, schemas.Unset] = schemas.unset,
        llmModel: typing.Union[MetaOapg.properties.llmModel, str, schemas.Unset] = schemas.unset,
        llmOrganization: typing.Union[MetaOapg.properties.llmOrganization, str, schemas.Unset] = schemas.unset,
        provider: typing.Union[MetaOapg.properties.provider, str, schemas.Unset] = schemas.unset,
        token: typing.Union[MetaOapg.properties.token, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ValidateLLMEndpointByIdRequest':
        return super().__new__(
            cls,
            *_args,
            baseUrl=baseUrl,
            llmModel=llmModel,
            llmOrganization=llmOrganization,
            provider=provider,
            token=token,
            _configuration=_configuration,
            **kwargs,
        )
