# (C) 2023 GoodData Corporation
version: 3

project:
  id: gooddata-python-sdk

telemetry:
  scope: 'off'

targets:
  only:
    - type: pipenv
      path: gooddata-pandas

paths:
  only:
    - gooddata-pandas
