# (C) 2023 GoodData Corporation
version: 3

project:
  id: gooddata-python-sdk

telemetry:
  scope: 'off'

# We need to specify it per-each package. See fossa_* branches.
# targets:
#   only:
#     - type: pipenv
#       path: path-here
#
# paths:
#   only:
#     - path-here
