from gooddata_api_client.paths.api_v1_actions_workspaces_workspace_id_analytical_dashboards_dashboard_id_available_assignees.get import ApiForget


class ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdAvailableAssignees(
    ApiForget,
):
    pass
