name: Hugo Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: docs
  hugo-env:
    required: false
    description: Environment variable
    default: public

runs:
  using: "composite"
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'
        extended: true
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: bash
    - name: Cache hugo dependencies
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('docs/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    - name: Build
      working-directory: ${{ inputs.working-directory }}
      env:
        HUGO_ENV: ${{ inputs.hugo-env }}
        BASE_URL: ${{ inputs.base-url }}
      run: hugo --minify ${BASE_URL:+--baseURL $BASE_URL} --debug
      shell: bash
