name: Hugo Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: true
    description: Base url used during build

runs:
  using: "composite"
  steps:
    - name: "Setup GO"
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.1'
    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json
    - name: "Install Hugo"
      shell: bash
      working-directory: ./docs
      run: |
        npm install -g hugo-extended@0.117.0
    - name: "Install Dependencies"
      shell: bash
      working-directory: ./docs
      run: |
        npm ci
    - name: "Build documentation"
      working-directory: ./docs
      env:
        BASE_URL: ${{ inputs.base-url }}
      shell: bash
      run: |
        hugo --minify ${BASE_URL:+--baseURL $BASE_URL} -e _default
