name: Hugo Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: docs
  hugo-env:
    required: false
    description: Environment variable
    default: public
  keep-master:
    required: false
    description: Preview of the master branch
    default: no
  fetch-from:
    required: false
    description: repo to fetch the versions from
    default: origin

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version-file: ".python-version"
      cache: 'pip'
      cache-dependency-path: scripts/script-requirements.txt
  - name: Install Dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r scripts/script-requirements.txt
  - uses: actions/setup-go@v4
    with:
      go-version: '>=1.20.1'
  - uses: actions/setup-node@v3
    with:
      node-version: 18
  - name: Install dependencies
    working-directory: ${{ inputs.working-directory }}
    run: npm ci
    shell: bash
  - name: "Setup Hugo"
    uses: peaceiris/actions-hugo@v2
    with:
      extended: true
      hugo-version: '0.110.0'
  - name: "Build"
    env:
      KEEP_MASTER: ${{ inputs.keep-master }}
      THIS_BRANCH: ${{ inputs.this-branch }}
      BASE_URL: ${{ inputs.base-url }}
      HUGO_ENV: production
    shell: bash
    run: |
      cd docs
      rm -f generate.sh
      wget https://raw.githubusercontent.com/gooddata/gooddata-python-sdk/master/scripts/generate.sh
      chmod +x ./generate.sh
      ./generate.sh ${{ inputs.fetch-from }} master ${{ inputs.keep-master}}
      npm install
      hugo version
      hugo --minify ${BASE_URL:+--baseURL $BASE_URL}
