# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from gooddata_api_client.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    ANALYTICS_MODEL = "Analytics Model"
    AVAILABLE_DRIVERS = "Available Drivers"
    COMPUTATION = "Computation"
    DATA_FILTERS = "Data Filters"
    DATA_SOURCE__DECLARATIVE_APIS = "Data Source - Declarative APIs"
    DEPENDENCY_GRAPH = "Dependency Graph"
    ENTITLEMENT = "Entitlement"
    GENERATE_LOGICAL_DATA_MODEL = "Generate Logical Data Model"
    INVALIDATE_CACHE = "Invalidate Cache"
    LDM__DECLARATIVE_APIS = "LDM - Declarative APIs"
    OPTIONS = "Options"
    ORGANIZATION__DECLARATIVE_APIS = "Organization - Declarative APIs"
    ORGANIZATION__ENTITY_APIS = "Organization - Entity APIs"
    PDM__DECLARATIVE_APIS = "PDM - Declarative APIs"
    PERMISSIONS = "Permissions"
    REPORTING__SETTINGS = "Reporting - Settings"
    SCANNING = "Scanning"
    TEST_CONNECTION = "Test Connection"
    USAGE = "Usage"
    USER_DATA_FILTERS = "User Data Filters"
    USER_GROUPS__DECLARATIVE_APIS = "UserGroups - Declarative APIs"
    USERS__DECLARATIVE_APIS = "Users - Declarative APIs"
    WORKSPACES__DECLARATIVE_APIS = "Workspaces - Declarative APIs"
    WORKSPACES__SETTINGS = "Workspaces - Settings"
    ACTIONS = "actions"
    ENTITIES = "entities"
    LAYOUT = "layout"
    API_TOKENS = "API tokens"
    USERMODELCONTROLLER = "user-model-controller"
    APPEARANCE = "Appearance"
    ORGANIZATIONMODELCONTROLLER = "organization-model-controller"
    ATTRIBUTES = "Attributes"
    WORKSPACEOBJECTCONTROLLER = "workspace-object-controller"
    CSP_DIRECTIVES = "CSP Directives"
    CONTEXT_FILTERS = "Context Filters"
    COOKIE_SECURITY_CONFIGURATION = "Cookie Security Configuration"
    ORGANIZATIONCONTROLLER = "organization-controller"
    DASHBOARDS = "Dashboards"
    DATA_SOURCE__ENTITY_APIS = "Data Source - Entity APIs"
    DATASOURCEENTITIESCONTROLLER = "data-source-entities-controller"
    DATASETS = "Datasets"
    EXPORTING = "Exporting"
    FACTS = "Facts"
    LABELS = "Labels"
    METRICS = "Metrics"
    PLUGINS = "Plugins"
    USER_SETTINGS = "User Settings"
    USER_GROUPS__ENTITY_APIS = "UserGroups - Entity APIs"
    USERS__ENTITY_APIS = "Users - Entity APIs"
    VISUALIZATION_OBJECT = "Visualization Object"
    WORKSPACES__ENTITY_APIS = "Workspaces - Entity APIs"
