# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from gooddata_api_client.paths.api_v1_actions_workspaces_workspace_id_export_raw.post import CreateRawExport
from gooddata_api_client.paths.api_v1_actions_workspaces_workspace_id_export_raw_export_id.get import GetRawExport


class RawExportApi(
    CreateRawExport,
    GetRawExport,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
