# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by: https://openapi-generator.tech
"""

from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects.post import CreateEntityVisualizationObjects
from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects_object_id.delete import DeleteEntityVisualizationObjects
from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects.get import GetAllEntitiesVisualizationObjects
from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects_object_id.get import GetEntityVisualizationObjects
from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects_object_id.patch import PatchEntityVisualizationObjects
from gooddata_api_client.paths.api_v1_entities_workspaces_workspace_id_visualization_objects_object_id.put import UpdateEntityVisualizationObjects


class VisualizationObjectApi(
    CreateEntityVisualizationObjects,
    DeleteEntityVisualizationObjects,
    GetAllEntitiesVisualizationObjects,
    GetEntityVisualizationObjects,
    PatchEntityVisualizationObjects,
    UpdateEntityVisualizationObjects,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
