name: Hugo Versioned Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: docs
  hugo-env:
    required: false
    description: Environment variable
    default: production
  keep_master:
    required: false
    description: Preview of the master branch
    default: no

runs:
  using: "composite"
  steps:
    - name: Generate Versioned Documentation
      shell: bash
      run: |
        cd docs
        ../scripts/generate.sh origin ${{ github.ref_name }}
    - name: Hugo Build
      uses: ./.github/actions/hugo-build-action
      with:
        hugo-env: ${{ inputs.hugo-env }}
        working-directory: ${{ inputs.working-directory }}
        base-url: ${{ inputs.base-url }}
