name: Hugo Versioned Build
description: Builds versioned documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: docs
  hugo-env:
    required: false
    description: Environment variable
    default: production
  fetch-from:
    required: false
    description: repo to fetch the versions from
    default: origin

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: 'pip'
        cache-dependency-path: scripts/script-requirements.txt
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/script-requirements.txt
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.1'
    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json
    - name: "Install Hugo"
      shell: bash
      working-directory: ./docs
      run: |
        npm install -g hugo-extended@0.117.0
    - name: "Install Dependencies"
      working-directory: ./docs
      shell: bash
      run: |
        npm ci
    - name: "Generate version docs"
      working-directory: ./docs
      shell: bash
      run: |
        rm -f generate.sh
        wget https://raw.githubusercontent.com/gooddata/gooddata-python-sdk/master/scripts/generate.sh
        chmod +x ./generate.sh
        ./generate.sh ${{ inputs.fetch-from }} master
    - name: "Build documentation"
      working-directory: ./docs
      env:
        THIS_BRANCH: ${{ inputs.this-branch }}
        BASE_URL: ${{ inputs.base-url }}
        HUGO_ENV: ${{ inputs.hugo-env }}
      shell: bash
      run: |
        hugo --minify ${BASE_URL:+--baseURL $BASE_URL}
