import typing_extensions

from gooddata_api_client.paths import PathValues
from gooddata_api_client.apis.paths.api_v1_actions_collect_usage import ApiV1ActionsCollectUsage
from gooddata_api_client.apis.paths.api_v1_actions_data_source_test import ApiV1ActionsDataSourceTest
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_generate_logical_model import ApiV1ActionsDataSourcesDataSourceIdGenerateLogicalModel
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_scan import ApiV1ActionsDataSourcesDataSourceIdScan
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_scan_schemata import ApiV1ActionsDataSourcesDataSourceIdScanSchemata
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_scan_sql import ApiV1ActionsDataSourcesDataSourceIdScanSql
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_test import ApiV1ActionsDataSourcesDataSourceIdTest
from gooddata_api_client.apis.paths.api_v1_actions_data_sources_data_source_id_upload_notification import ApiV1ActionsDataSourcesDataSourceIdUploadNotification
from gooddata_api_client.apis.paths.api_v1_actions_resolve_entitlements import ApiV1ActionsResolveEntitlements
from gooddata_api_client.apis.paths.api_v1_actions_resolve_settings import ApiV1ActionsResolveSettings
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_analytical_dashboards_dashboard_id_available_assignees import ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdAvailableAssignees
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_analytical_dashboards_dashboard_id_manage_permissions import ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdManagePermissions
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_analytical_dashboards_dashboard_id_permissions import ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdPermissions
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_check_entity_overrides import ApiV1ActionsWorkspacesWorkspaceIdCheckEntityOverrides
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_dependent_entities_graph import ApiV1ActionsWorkspacesWorkspaceIdDependentEntitiesGraph
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_afm_compute_valid_objects import ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmComputeValidObjects
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_afm_execute import ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecute
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_afm_execute_result_result_id import ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultId
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_afm_execute_result_result_id_metadata import ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultIdMetadata
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_afm_explain import ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExplain
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_execution_collect_label_elements import ApiV1ActionsWorkspacesWorkspaceIdExecutionCollectLabelElements
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_export_tabular import ApiV1ActionsWorkspacesWorkspaceIdExportTabular
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_export_tabular_export_id import ApiV1ActionsWorkspacesWorkspaceIdExportTabularExportId
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_export_visual import ApiV1ActionsWorkspacesWorkspaceIdExportVisual
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_export_visual_export_id import ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportId
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_export_visual_export_id_metadata import ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportIdMetadata
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_inherited_entity_conflicts import ApiV1ActionsWorkspacesWorkspaceIdInheritedEntityConflicts
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_overridden_child_entities import ApiV1ActionsWorkspacesWorkspaceIdOverriddenChildEntities
from gooddata_api_client.apis.paths.api_v1_actions_workspaces_workspace_id_resolve_settings import ApiV1ActionsWorkspacesWorkspaceIdResolveSettings
from gooddata_api_client.apis.paths.api_v1_entities_admin_cookie_security_configurations_id import ApiV1EntitiesAdminCookieSecurityConfigurationsId
from gooddata_api_client.apis.paths.api_v1_entities_admin_organizations_id import ApiV1EntitiesAdminOrganizationsId
from gooddata_api_client.apis.paths.api_v1_entities_color_palettes import ApiV1EntitiesColorPalettes
from gooddata_api_client.apis.paths.api_v1_entities_color_palettes_id import ApiV1EntitiesColorPalettesId
from gooddata_api_client.apis.paths.api_v1_entities_csp_directives import ApiV1EntitiesCspDirectives
from gooddata_api_client.apis.paths.api_v1_entities_csp_directives_id import ApiV1EntitiesCspDirectivesId
from gooddata_api_client.apis.paths.api_v1_entities_data_source_identifiers import ApiV1EntitiesDataSourceIdentifiers
from gooddata_api_client.apis.paths.api_v1_entities_data_source_identifiers_id import ApiV1EntitiesDataSourceIdentifiersId
from gooddata_api_client.apis.paths.api_v1_entities_data_sources import ApiV1EntitiesDataSources
from gooddata_api_client.apis.paths.api_v1_entities_data_sources_data_source_id_data_source_tables import ApiV1EntitiesDataSourcesDataSourceIdDataSourceTables
from gooddata_api_client.apis.paths.api_v1_entities_data_sources_data_source_id_data_source_tables_id import ApiV1EntitiesDataSourcesDataSourceIdDataSourceTablesId
from gooddata_api_client.apis.paths.api_v1_entities_data_sources_id import ApiV1EntitiesDataSourcesId
from gooddata_api_client.apis.paths.api_v1_entities_entitlements import ApiV1EntitiesEntitlements
from gooddata_api_client.apis.paths.api_v1_entities_entitlements_id import ApiV1EntitiesEntitlementsId
from gooddata_api_client.apis.paths.api_v1_entities_organization import ApiV1EntitiesOrganization
from gooddata_api_client.apis.paths.api_v1_entities_organization_settings import ApiV1EntitiesOrganizationSettings
from gooddata_api_client.apis.paths.api_v1_entities_organization_settings_id import ApiV1EntitiesOrganizationSettingsId
from gooddata_api_client.apis.paths.api_v1_entities_themes import ApiV1EntitiesThemes
from gooddata_api_client.apis.paths.api_v1_entities_themes_id import ApiV1EntitiesThemesId
from gooddata_api_client.apis.paths.api_v1_entities_user_groups import ApiV1EntitiesUserGroups
from gooddata_api_client.apis.paths.api_v1_entities_user_groups_id import ApiV1EntitiesUserGroupsId
from gooddata_api_client.apis.paths.api_v1_entities_users import ApiV1EntitiesUsers
from gooddata_api_client.apis.paths.api_v1_entities_users_id import ApiV1EntitiesUsersId
from gooddata_api_client.apis.paths.api_v1_entities_users_user_id_api_tokens import ApiV1EntitiesUsersUserIdApiTokens
from gooddata_api_client.apis.paths.api_v1_entities_users_user_id_api_tokens_id import ApiV1EntitiesUsersUserIdApiTokensId
from gooddata_api_client.apis.paths.api_v1_entities_users_user_id_user_settings import ApiV1EntitiesUsersUserIdUserSettings
from gooddata_api_client.apis.paths.api_v1_entities_users_user_id_user_settings_id import ApiV1EntitiesUsersUserIdUserSettingsId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces import ApiV1EntitiesWorkspaces
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_id import ApiV1EntitiesWorkspacesId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_analytical_dashboards import ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboards
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_analytical_dashboards_object_id import ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboardsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_attributes import ApiV1EntitiesWorkspacesWorkspaceIdAttributes
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_attributes_object_id import ApiV1EntitiesWorkspacesWorkspaceIdAttributesObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_custom_application_settings import ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettings
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_custom_application_settings_object_id import ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettingsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_dashboard_plugins import ApiV1EntitiesWorkspacesWorkspaceIdDashboardPlugins
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_dashboard_plugins_object_id import ApiV1EntitiesWorkspacesWorkspaceIdDashboardPluginsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_datasets import ApiV1EntitiesWorkspacesWorkspaceIdDatasets
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_datasets_object_id import ApiV1EntitiesWorkspacesWorkspaceIdDatasetsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_facts import ApiV1EntitiesWorkspacesWorkspaceIdFacts
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_facts_object_id import ApiV1EntitiesWorkspacesWorkspaceIdFactsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_filter_contexts import ApiV1EntitiesWorkspacesWorkspaceIdFilterContexts
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_filter_contexts_object_id import ApiV1EntitiesWorkspacesWorkspaceIdFilterContextsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_labels import ApiV1EntitiesWorkspacesWorkspaceIdLabels
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_labels_object_id import ApiV1EntitiesWorkspacesWorkspaceIdLabelsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_metrics import ApiV1EntitiesWorkspacesWorkspaceIdMetrics
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_metrics_object_id import ApiV1EntitiesWorkspacesWorkspaceIdMetricsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_user_data_filters import ApiV1EntitiesWorkspacesWorkspaceIdUserDataFilters
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_user_data_filters_object_id import ApiV1EntitiesWorkspacesWorkspaceIdUserDataFiltersObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_visualization_objects import ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjects
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_visualization_objects_object_id import ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjectsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_data_filter_settings import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettings
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_data_filter_settings_object_id import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettingsObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_data_filters import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilters
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_data_filters_object_id import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFiltersObjectId
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_settings import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettings
from gooddata_api_client.apis.paths.api_v1_entities_workspaces_workspace_id_workspace_settings_object_id import ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettingsObjectId
from gooddata_api_client.apis.paths.api_v1_layout_data_sources import ApiV1LayoutDataSources
from gooddata_api_client.apis.paths.api_v1_layout_data_sources_data_source_id_physical_model import ApiV1LayoutDataSourcesDataSourceIdPhysicalModel
from gooddata_api_client.apis.paths.api_v1_layout_organization import ApiV1LayoutOrganization
from gooddata_api_client.apis.paths.api_v1_layout_user_groups import ApiV1LayoutUserGroups
from gooddata_api_client.apis.paths.api_v1_layout_user_groups_user_group_id_permissions import ApiV1LayoutUserGroupsUserGroupIdPermissions
from gooddata_api_client.apis.paths.api_v1_layout_users import ApiV1LayoutUsers
from gooddata_api_client.apis.paths.api_v1_layout_users_user_id_permissions import ApiV1LayoutUsersUserIdPermissions
from gooddata_api_client.apis.paths.api_v1_layout_users_and_user_groups import ApiV1LayoutUsersAndUserGroups
from gooddata_api_client.apis.paths.api_v1_layout_workspace_data_filters import ApiV1LayoutWorkspaceDataFilters
from gooddata_api_client.apis.paths.api_v1_layout_workspaces import ApiV1LayoutWorkspaces
from gooddata_api_client.apis.paths.api_v1_layout_workspaces_workspace_id import ApiV1LayoutWorkspacesWorkspaceId
from gooddata_api_client.apis.paths.api_v1_layout_workspaces_workspace_id_analytics_model import ApiV1LayoutWorkspacesWorkspaceIdAnalyticsModel
from gooddata_api_client.apis.paths.api_v1_layout_workspaces_workspace_id_logical_model import ApiV1LayoutWorkspacesWorkspaceIdLogicalModel
from gooddata_api_client.apis.paths.api_v1_layout_workspaces_workspace_id_permissions import ApiV1LayoutWorkspacesWorkspaceIdPermissions
from gooddata_api_client.apis.paths.api_v1_layout_workspaces_workspace_id_user_data_filters import ApiV1LayoutWorkspacesWorkspaceIdUserDataFilters
from gooddata_api_client.apis.paths.api_v1_options import ApiV1Options
from gooddata_api_client.apis.paths.api_v1_options_available_drivers import ApiV1OptionsAvailableDrivers

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_V1_ACTIONS_COLLECT_USAGE: ApiV1ActionsCollectUsage,
        PathValues.API_V1_ACTIONS_DATA_SOURCE_TEST: ApiV1ActionsDataSourceTest,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_GENERATE_LOGICAL_MODEL: ApiV1ActionsDataSourcesDataSourceIdGenerateLogicalModel,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN: ApiV1ActionsDataSourcesDataSourceIdScan,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN_SCHEMATA: ApiV1ActionsDataSourcesDataSourceIdScanSchemata,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN_SQL: ApiV1ActionsDataSourcesDataSourceIdScanSql,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_TEST: ApiV1ActionsDataSourcesDataSourceIdTest,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_UPLOAD_NOTIFICATION: ApiV1ActionsDataSourcesDataSourceIdUploadNotification,
        PathValues.API_V1_ACTIONS_RESOLVE_ENTITLEMENTS: ApiV1ActionsResolveEntitlements,
        PathValues.API_V1_ACTIONS_RESOLVE_SETTINGS: ApiV1ActionsResolveSettings,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_AVAILABLE_ASSIGNEES: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdAvailableAssignees,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_MANAGE_PERMISSIONS: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdManagePermissions,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_PERMISSIONS: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdPermissions,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_CHECK_ENTITY_OVERRIDES: ApiV1ActionsWorkspacesWorkspaceIdCheckEntityOverrides,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_DEPENDENT_ENTITIES_GRAPH: ApiV1ActionsWorkspacesWorkspaceIdDependentEntitiesGraph,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_COMPUTE_VALID_OBJECTS: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmComputeValidObjects,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecute,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE_RESULT_RESULT_ID: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE_RESULT_RESULT_ID_METADATA: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultIdMetadata,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXPLAIN: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExplain,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_COLLECT_LABEL_ELEMENTS: ApiV1ActionsWorkspacesWorkspaceIdExecutionCollectLabelElements,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_TABULAR: ApiV1ActionsWorkspacesWorkspaceIdExportTabular,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_TABULAR_EXPORT_ID: ApiV1ActionsWorkspacesWorkspaceIdExportTabularExportId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL: ApiV1ActionsWorkspacesWorkspaceIdExportVisual,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL_EXPORT_ID: ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL_EXPORT_ID_METADATA: ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportIdMetadata,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_INHERITED_ENTITY_CONFLICTS: ApiV1ActionsWorkspacesWorkspaceIdInheritedEntityConflicts,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_OVERRIDDEN_CHILD_ENTITIES: ApiV1ActionsWorkspacesWorkspaceIdOverriddenChildEntities,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_RESOLVE_SETTINGS: ApiV1ActionsWorkspacesWorkspaceIdResolveSettings,
        PathValues.API_V1_ENTITIES_ADMIN_COOKIE_SECURITY_CONFIGURATIONS_ID: ApiV1EntitiesAdminCookieSecurityConfigurationsId,
        PathValues.API_V1_ENTITIES_ADMIN_ORGANIZATIONS_ID: ApiV1EntitiesAdminOrganizationsId,
        PathValues.API_V1_ENTITIES_COLOR_PALETTES: ApiV1EntitiesColorPalettes,
        PathValues.API_V1_ENTITIES_COLOR_PALETTES_ID: ApiV1EntitiesColorPalettesId,
        PathValues.API_V1_ENTITIES_CSP_DIRECTIVES: ApiV1EntitiesCspDirectives,
        PathValues.API_V1_ENTITIES_CSP_DIRECTIVES_ID: ApiV1EntitiesCspDirectivesId,
        PathValues.API_V1_ENTITIES_DATA_SOURCE_IDENTIFIERS: ApiV1EntitiesDataSourceIdentifiers,
        PathValues.API_V1_ENTITIES_DATA_SOURCE_IDENTIFIERS_ID: ApiV1EntitiesDataSourceIdentifiersId,
        PathValues.API_V1_ENTITIES_DATA_SOURCES: ApiV1EntitiesDataSources,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_DATA_SOURCE_ID_DATA_SOURCE_TABLES: ApiV1EntitiesDataSourcesDataSourceIdDataSourceTables,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_DATA_SOURCE_ID_DATA_SOURCE_TABLES_ID: ApiV1EntitiesDataSourcesDataSourceIdDataSourceTablesId,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_ID: ApiV1EntitiesDataSourcesId,
        PathValues.API_V1_ENTITIES_ENTITLEMENTS: ApiV1EntitiesEntitlements,
        PathValues.API_V1_ENTITIES_ENTITLEMENTS_ID: ApiV1EntitiesEntitlementsId,
        PathValues.API_V1_ENTITIES_ORGANIZATION: ApiV1EntitiesOrganization,
        PathValues.API_V1_ENTITIES_ORGANIZATION_SETTINGS: ApiV1EntitiesOrganizationSettings,
        PathValues.API_V1_ENTITIES_ORGANIZATION_SETTINGS_ID: ApiV1EntitiesOrganizationSettingsId,
        PathValues.API_V1_ENTITIES_THEMES: ApiV1EntitiesThemes,
        PathValues.API_V1_ENTITIES_THEMES_ID: ApiV1EntitiesThemesId,
        PathValues.API_V1_ENTITIES_USER_GROUPS: ApiV1EntitiesUserGroups,
        PathValues.API_V1_ENTITIES_USER_GROUPS_ID: ApiV1EntitiesUserGroupsId,
        PathValues.API_V1_ENTITIES_USERS: ApiV1EntitiesUsers,
        PathValues.API_V1_ENTITIES_USERS_ID: ApiV1EntitiesUsersId,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_API_TOKENS: ApiV1EntitiesUsersUserIdApiTokens,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_API_TOKENS_ID: ApiV1EntitiesUsersUserIdApiTokensId,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_USER_SETTINGS: ApiV1EntitiesUsersUserIdUserSettings,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_USER_SETTINGS_ID: ApiV1EntitiesUsersUserIdUserSettingsId,
        PathValues.API_V1_ENTITIES_WORKSPACES: ApiV1EntitiesWorkspaces,
        PathValues.API_V1_ENTITIES_WORKSPACES_ID: ApiV1EntitiesWorkspacesId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS: ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboards,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboardsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ATTRIBUTES: ApiV1EntitiesWorkspacesWorkspaceIdAttributes,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ATTRIBUTES_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdAttributesObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_CUSTOM_APPLICATION_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_CUSTOM_APPLICATION_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettingsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DASHBOARD_PLUGINS: ApiV1EntitiesWorkspacesWorkspaceIdDashboardPlugins,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DASHBOARD_PLUGINS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdDashboardPluginsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DATASETS: ApiV1EntitiesWorkspacesWorkspaceIdDatasets,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DATASETS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdDatasetsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FACTS: ApiV1EntitiesWorkspacesWorkspaceIdFacts,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FACTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdFactsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FILTER_CONTEXTS: ApiV1EntitiesWorkspacesWorkspaceIdFilterContexts,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FILTER_CONTEXTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdFilterContextsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_LABELS: ApiV1EntitiesWorkspacesWorkspaceIdLabels,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_LABELS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdLabelsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_METRICS: ApiV1EntitiesWorkspacesWorkspaceIdMetrics,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_METRICS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdMetricsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS: ApiV1EntitiesWorkspacesWorkspaceIdUserDataFilters,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdUserDataFiltersObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_VISUALIZATION_OBJECTS: ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjects,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_VISUALIZATION_OBJECTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjectsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTER_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTER_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettingsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTERS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilters,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTERS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFiltersObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettingsObjectId,
        PathValues.API_V1_LAYOUT_DATA_SOURCES: ApiV1LayoutDataSources,
        PathValues.API_V1_LAYOUT_DATA_SOURCES_DATA_SOURCE_ID_PHYSICAL_MODEL: ApiV1LayoutDataSourcesDataSourceIdPhysicalModel,
        PathValues.API_V1_LAYOUT_ORGANIZATION: ApiV1LayoutOrganization,
        PathValues.API_V1_LAYOUT_USER_GROUPS: ApiV1LayoutUserGroups,
        PathValues.API_V1_LAYOUT_USER_GROUPS_USER_GROUP_ID_PERMISSIONS: ApiV1LayoutUserGroupsUserGroupIdPermissions,
        PathValues.API_V1_LAYOUT_USERS: ApiV1LayoutUsers,
        PathValues.API_V1_LAYOUT_USERS_USER_ID_PERMISSIONS: ApiV1LayoutUsersUserIdPermissions,
        PathValues.API_V1_LAYOUT_USERS_AND_USER_GROUPS: ApiV1LayoutUsersAndUserGroups,
        PathValues.API_V1_LAYOUT_WORKSPACE_DATA_FILTERS: ApiV1LayoutWorkspaceDataFilters,
        PathValues.API_V1_LAYOUT_WORKSPACES: ApiV1LayoutWorkspaces,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID: ApiV1LayoutWorkspacesWorkspaceId,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_ANALYTICS_MODEL: ApiV1LayoutWorkspacesWorkspaceIdAnalyticsModel,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_LOGICAL_MODEL: ApiV1LayoutWorkspacesWorkspaceIdLogicalModel,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_PERMISSIONS: ApiV1LayoutWorkspacesWorkspaceIdPermissions,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS: ApiV1LayoutWorkspacesWorkspaceIdUserDataFilters,
        PathValues.API_V1_OPTIONS: ApiV1Options,
        PathValues.API_V1_OPTIONS_AVAILABLE_DRIVERS: ApiV1OptionsAvailableDrivers,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_V1_ACTIONS_COLLECT_USAGE: ApiV1ActionsCollectUsage,
        PathValues.API_V1_ACTIONS_DATA_SOURCE_TEST: ApiV1ActionsDataSourceTest,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_GENERATE_LOGICAL_MODEL: ApiV1ActionsDataSourcesDataSourceIdGenerateLogicalModel,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN: ApiV1ActionsDataSourcesDataSourceIdScan,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN_SCHEMATA: ApiV1ActionsDataSourcesDataSourceIdScanSchemata,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_SCAN_SQL: ApiV1ActionsDataSourcesDataSourceIdScanSql,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_TEST: ApiV1ActionsDataSourcesDataSourceIdTest,
        PathValues.API_V1_ACTIONS_DATA_SOURCES_DATA_SOURCE_ID_UPLOAD_NOTIFICATION: ApiV1ActionsDataSourcesDataSourceIdUploadNotification,
        PathValues.API_V1_ACTIONS_RESOLVE_ENTITLEMENTS: ApiV1ActionsResolveEntitlements,
        PathValues.API_V1_ACTIONS_RESOLVE_SETTINGS: ApiV1ActionsResolveSettings,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_AVAILABLE_ASSIGNEES: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdAvailableAssignees,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_MANAGE_PERMISSIONS: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdManagePermissions,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_DASHBOARD_ID_PERMISSIONS: ApiV1ActionsWorkspacesWorkspaceIdAnalyticalDashboardsDashboardIdPermissions,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_CHECK_ENTITY_OVERRIDES: ApiV1ActionsWorkspacesWorkspaceIdCheckEntityOverrides,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_DEPENDENT_ENTITIES_GRAPH: ApiV1ActionsWorkspacesWorkspaceIdDependentEntitiesGraph,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_COMPUTE_VALID_OBJECTS: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmComputeValidObjects,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecute,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE_RESULT_RESULT_ID: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXECUTE_RESULT_RESULT_ID_METADATA: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExecuteResultResultIdMetadata,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_AFM_EXPLAIN: ApiV1ActionsWorkspacesWorkspaceIdExecutionAfmExplain,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXECUTION_COLLECT_LABEL_ELEMENTS: ApiV1ActionsWorkspacesWorkspaceIdExecutionCollectLabelElements,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_TABULAR: ApiV1ActionsWorkspacesWorkspaceIdExportTabular,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_TABULAR_EXPORT_ID: ApiV1ActionsWorkspacesWorkspaceIdExportTabularExportId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL: ApiV1ActionsWorkspacesWorkspaceIdExportVisual,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL_EXPORT_ID: ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportId,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_EXPORT_VISUAL_EXPORT_ID_METADATA: ApiV1ActionsWorkspacesWorkspaceIdExportVisualExportIdMetadata,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_INHERITED_ENTITY_CONFLICTS: ApiV1ActionsWorkspacesWorkspaceIdInheritedEntityConflicts,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_OVERRIDDEN_CHILD_ENTITIES: ApiV1ActionsWorkspacesWorkspaceIdOverriddenChildEntities,
        PathValues.API_V1_ACTIONS_WORKSPACES_WORKSPACE_ID_RESOLVE_SETTINGS: ApiV1ActionsWorkspacesWorkspaceIdResolveSettings,
        PathValues.API_V1_ENTITIES_ADMIN_COOKIE_SECURITY_CONFIGURATIONS_ID: ApiV1EntitiesAdminCookieSecurityConfigurationsId,
        PathValues.API_V1_ENTITIES_ADMIN_ORGANIZATIONS_ID: ApiV1EntitiesAdminOrganizationsId,
        PathValues.API_V1_ENTITIES_COLOR_PALETTES: ApiV1EntitiesColorPalettes,
        PathValues.API_V1_ENTITIES_COLOR_PALETTES_ID: ApiV1EntitiesColorPalettesId,
        PathValues.API_V1_ENTITIES_CSP_DIRECTIVES: ApiV1EntitiesCspDirectives,
        PathValues.API_V1_ENTITIES_CSP_DIRECTIVES_ID: ApiV1EntitiesCspDirectivesId,
        PathValues.API_V1_ENTITIES_DATA_SOURCE_IDENTIFIERS: ApiV1EntitiesDataSourceIdentifiers,
        PathValues.API_V1_ENTITIES_DATA_SOURCE_IDENTIFIERS_ID: ApiV1EntitiesDataSourceIdentifiersId,
        PathValues.API_V1_ENTITIES_DATA_SOURCES: ApiV1EntitiesDataSources,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_DATA_SOURCE_ID_DATA_SOURCE_TABLES: ApiV1EntitiesDataSourcesDataSourceIdDataSourceTables,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_DATA_SOURCE_ID_DATA_SOURCE_TABLES_ID: ApiV1EntitiesDataSourcesDataSourceIdDataSourceTablesId,
        PathValues.API_V1_ENTITIES_DATA_SOURCES_ID: ApiV1EntitiesDataSourcesId,
        PathValues.API_V1_ENTITIES_ENTITLEMENTS: ApiV1EntitiesEntitlements,
        PathValues.API_V1_ENTITIES_ENTITLEMENTS_ID: ApiV1EntitiesEntitlementsId,
        PathValues.API_V1_ENTITIES_ORGANIZATION: ApiV1EntitiesOrganization,
        PathValues.API_V1_ENTITIES_ORGANIZATION_SETTINGS: ApiV1EntitiesOrganizationSettings,
        PathValues.API_V1_ENTITIES_ORGANIZATION_SETTINGS_ID: ApiV1EntitiesOrganizationSettingsId,
        PathValues.API_V1_ENTITIES_THEMES: ApiV1EntitiesThemes,
        PathValues.API_V1_ENTITIES_THEMES_ID: ApiV1EntitiesThemesId,
        PathValues.API_V1_ENTITIES_USER_GROUPS: ApiV1EntitiesUserGroups,
        PathValues.API_V1_ENTITIES_USER_GROUPS_ID: ApiV1EntitiesUserGroupsId,
        PathValues.API_V1_ENTITIES_USERS: ApiV1EntitiesUsers,
        PathValues.API_V1_ENTITIES_USERS_ID: ApiV1EntitiesUsersId,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_API_TOKENS: ApiV1EntitiesUsersUserIdApiTokens,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_API_TOKENS_ID: ApiV1EntitiesUsersUserIdApiTokensId,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_USER_SETTINGS: ApiV1EntitiesUsersUserIdUserSettings,
        PathValues.API_V1_ENTITIES_USERS_USER_ID_USER_SETTINGS_ID: ApiV1EntitiesUsersUserIdUserSettingsId,
        PathValues.API_V1_ENTITIES_WORKSPACES: ApiV1EntitiesWorkspaces,
        PathValues.API_V1_ENTITIES_WORKSPACES_ID: ApiV1EntitiesWorkspacesId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS: ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboards,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ANALYTICAL_DASHBOARDS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdAnalyticalDashboardsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ATTRIBUTES: ApiV1EntitiesWorkspacesWorkspaceIdAttributes,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_ATTRIBUTES_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdAttributesObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_CUSTOM_APPLICATION_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_CUSTOM_APPLICATION_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdCustomApplicationSettingsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DASHBOARD_PLUGINS: ApiV1EntitiesWorkspacesWorkspaceIdDashboardPlugins,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DASHBOARD_PLUGINS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdDashboardPluginsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DATASETS: ApiV1EntitiesWorkspacesWorkspaceIdDatasets,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_DATASETS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdDatasetsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FACTS: ApiV1EntitiesWorkspacesWorkspaceIdFacts,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FACTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdFactsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FILTER_CONTEXTS: ApiV1EntitiesWorkspacesWorkspaceIdFilterContexts,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_FILTER_CONTEXTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdFilterContextsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_LABELS: ApiV1EntitiesWorkspacesWorkspaceIdLabels,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_LABELS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdLabelsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_METRICS: ApiV1EntitiesWorkspacesWorkspaceIdMetrics,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_METRICS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdMetricsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS: ApiV1EntitiesWorkspacesWorkspaceIdUserDataFilters,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdUserDataFiltersObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_VISUALIZATION_OBJECTS: ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjects,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_VISUALIZATION_OBJECTS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdVisualizationObjectsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTER_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTER_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilterSettingsObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTERS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFilters,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_DATA_FILTERS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceDataFiltersObjectId,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_SETTINGS: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettings,
        PathValues.API_V1_ENTITIES_WORKSPACES_WORKSPACE_ID_WORKSPACE_SETTINGS_OBJECT_ID: ApiV1EntitiesWorkspacesWorkspaceIdWorkspaceSettingsObjectId,
        PathValues.API_V1_LAYOUT_DATA_SOURCES: ApiV1LayoutDataSources,
        PathValues.API_V1_LAYOUT_DATA_SOURCES_DATA_SOURCE_ID_PHYSICAL_MODEL: ApiV1LayoutDataSourcesDataSourceIdPhysicalModel,
        PathValues.API_V1_LAYOUT_ORGANIZATION: ApiV1LayoutOrganization,
        PathValues.API_V1_LAYOUT_USER_GROUPS: ApiV1LayoutUserGroups,
        PathValues.API_V1_LAYOUT_USER_GROUPS_USER_GROUP_ID_PERMISSIONS: ApiV1LayoutUserGroupsUserGroupIdPermissions,
        PathValues.API_V1_LAYOUT_USERS: ApiV1LayoutUsers,
        PathValues.API_V1_LAYOUT_USERS_USER_ID_PERMISSIONS: ApiV1LayoutUsersUserIdPermissions,
        PathValues.API_V1_LAYOUT_USERS_AND_USER_GROUPS: ApiV1LayoutUsersAndUserGroups,
        PathValues.API_V1_LAYOUT_WORKSPACE_DATA_FILTERS: ApiV1LayoutWorkspaceDataFilters,
        PathValues.API_V1_LAYOUT_WORKSPACES: ApiV1LayoutWorkspaces,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID: ApiV1LayoutWorkspacesWorkspaceId,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_ANALYTICS_MODEL: ApiV1LayoutWorkspacesWorkspaceIdAnalyticsModel,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_LOGICAL_MODEL: ApiV1LayoutWorkspacesWorkspaceIdLogicalModel,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_PERMISSIONS: ApiV1LayoutWorkspacesWorkspaceIdPermissions,
        PathValues.API_V1_LAYOUT_WORKSPACES_WORKSPACE_ID_USER_DATA_FILTERS: ApiV1LayoutWorkspacesWorkspaceIdUserDataFilters,
        PathValues.API_V1_OPTIONS: ApiV1Options,
        PathValues.API_V1_OPTIONS_AVAILABLE_DRIVERS: ApiV1OptionsAvailableDrivers,
    }
)
