name: Netlify Preview Deploy
on:
  pull_request:
    branches:
      - master
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  NETLIFY_SITE_NAME: ${{ github.event.repository.name }}
jobs:
  netlify-preview-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Hugo Build
        uses: ./.github/actions/hugo-build-action
        with:
          BASE_URL: https://preview-$GITHUB_PR_NUMBER--$NETLIFY_SITE_NAME.netlify.app
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy -d gooddata-sdk/docs/hugo/docs/public --alias=preview-$GITHUB_PR_NUMBER
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
